// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesRental.Models;

#nullable disable

namespace MoviesRental.Migrations
{
    [DbContext(typeof(MovieRentalContext))]
    [Migration("20251126225213_validations1_new")]
    partial class validations1_new
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoviesRental.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CartId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("MoviesRental.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("RentalDays")
                        .HasColumnType("int");

                    b.HasKey("CartItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("MovieId");

                    b.ToTable("CartItems", t =>
                        {
                            t.HasCheckConstraint("CK_CartItem_Quantity_Range", "[Quantity] >= 1 AND [Quantity] <= 10");

                            t.HasCheckConstraint("CK_CartItem_RentalDays_Range", "[RentalDays] >= 1 AND [RentalDays] <= 30");
                        });
                });

            modelBuilder.Entity("MoviesRental.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ReleaseYear")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<decimal>("RentalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("MovieId")
                        .HasName("PK__Movies__4BD2941A6368F0F4");

                    b.ToTable("Movies", t =>
                        {
                            t.HasCheckConstraint("CK_Movies_Desc_MinLength", "LEN([Description]) >= 6");

                            t.HasCheckConstraint("CK_Movies_Genre_MinLength", "LEN([Genre]) >= 4");

                            t.HasCheckConstraint("CK_Movies_ReleaseYear_Range", "[ReleaseYear] >= 1801 AND [ReleaseYear] <= 2025");

                            t.HasCheckConstraint("CK_Movies_RentalPrice_Positive", "[RentalPrice] > 0");

                            t.HasCheckConstraint("CK_Movies_Stock_NonNegative", "[Stock] >= 0");

                            t.HasCheckConstraint("CK_Movies_Title_MinLength", "LEN([Title]) >= 4");
                        });
                });

            modelBuilder.Entity("MoviesRental.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("PaidOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RentalId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Completed");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__PaymentId");

                    b.HasIndex("RentalId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Payments", t =>
                        {
                            t.HasCheckConstraint("CK_Payments_Amount_Positive", "[Amount] > 0");

                            t.HasCheckConstraint("CK_Payments_PaymentMethod_MinLength", "LEN([PaymentMethod]) >= 3");

                            t.HasCheckConstraint("CK_Payments_Status_MinLength", "LEN([Status]) >= 3");
                        });
                });

            modelBuilder.Entity("MoviesRental.Models.Rental", b =>
                {
                    b.Property<int>("RentalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentalId"));

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime>("RentedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("ReturnedOn")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RentalId")
                        .HasName("PK__Rentals__970059430E888F41");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Rentals", t =>
                        {
                            t.HasCheckConstraint("CK_Rentals_DueDate_After_RentedOn", "[DueDate] > [RentedOn]");

                            t.HasCheckConstraint("CK_Rentals_Price_Positive", "[Price] > 0");

                            t.HasCheckConstraint("CK_Rentals_ReturnedOn_After_RentedOn", "[ReturnedOn] IS NULL OR [ReturnedOn] >= [RentedOn]");
                        });
                });

            modelBuilder.Entity("MoviesRental.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId")
                        .HasName("PK__Reviews__74BC79CEB4AE0A62");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews", t =>
                        {
                            t.HasCheckConstraint("CK_Reviews_Comment_MinLength", "LEN([Comment]) >= 5 OR [Comment] IS NULL");

                            t.HasCheckConstraint("CK_Reviews_Rating_Range", "[Rating] >= 1 AND [Rating] <= 5");
                        });
                });

            modelBuilder.Entity("MoviesRental.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C0C6F1E16");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_Email");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_Name");

                    b.HasIndex("Phone")
                        .IsUnique()
                        .HasDatabaseName("UQ_Users_Phone");

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Email_MinLength", "LEN([Email]) >= 4");

                            t.HasCheckConstraint("CK_Users_Name_MinLength", "LEN([Name]) >= 4");

                            t.HasCheckConstraint("CK_Users_Phone_10Digits", "LEN([Phone]) = 10 AND [Phone] NOT LIKE '%[^0-9]%'");

                            t.HasCheckConstraint("CK_Users_Role_Enum", "[Role] IN ('User','Admin')");
                        });
                });

            modelBuilder.Entity("MoviesRental.Models.Cart", b =>
                {
                    b.HasOne("MoviesRental.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoviesRental.Models.CartItem", b =>
                {
                    b.HasOne("MoviesRental.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoviesRental.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MoviesRental.Models.Payment", b =>
                {
                    b.HasOne("MoviesRental.Models.Rental", "Rental")
                        .WithOne("Payment")
                        .HasForeignKey("MoviesRental.Models.Payment", "RentalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoviesRental.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Rental");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoviesRental.Models.Rental", b =>
                {
                    b.HasOne("MoviesRental.Models.Movie", "Movie")
                        .WithMany("Rentals")
                        .HasForeignKey("MovieId")
                        .IsRequired()
                        .HasConstraintName("FK__Rentals__MovieId__403A8C7D");

                    b.HasOne("MoviesRental.Models.User", "User")
                        .WithMany("Rentals")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Rentals__UserId__3F466844");

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoviesRental.Models.Review", b =>
                {
                    b.HasOne("MoviesRental.Models.Movie", "Movie")
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId")
                        .IsRequired()
                        .HasConstraintName("FK__Reviews__MovieId__45F365D3");

                    b.HasOne("MoviesRental.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Reviews__UserId__44FF419A");

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MoviesRental.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("MoviesRental.Models.Movie", b =>
                {
                    b.Navigation("Rentals");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("MoviesRental.Models.Rental", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("MoviesRental.Models.User", b =>
                {
                    b.Navigation("Rentals");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
